language: go

go:
   - 1.6

install:
- export PATH=$PATH:$HOME/gopath/bin
- go get github.com/lcaballero/mime
- go get github.com/lcaballero/exam

script: cd $HOME/gopath/src/github.com/lcaballero/exam && go test --race ./...